server:
  port: 8181

applicationconstants:
  controllerconstants:
    person: test_value

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev   
  datasource:
    driver-class-name: org.postgresql.Driver
    password: backenduser
    url: jdbc:postgresql://172.17.0.1:5432/backend_test
    username: backenduser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest
welcome:
  message: Welcome to spring boot demo by Kyron!!

profileconstants:
  controllerconstants:
    person: test_value_profile_dev

kyron:
  rabbit:
    mq:
      queue:
        name: cola1

kafka:
  topic:
    person: spring-boot-demo-test
# actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
# exclude actuator endpoints
---

spring:
  profiles: qa  
  datasource:
    driver-class-name: org.postgresql.Driver
    password: backenduser
    url: jdbc:postgresql://172.17.0.1:5432/backend_test
    username: backenduser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest
welcome:
  message: Welcome to spring boot demo by Kyron!!
  
profileconstants:
  controllerconstants:
    person: test_value_profile_qa
kyron:
  rabbit:
    mq:
      queue:
        name: cola1

kafka:
  topic:
    person: spring-boot-demo-test
# actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
# exclude actuator endpoints
---

spring:
  profiles: prod  
  datasource:
    driver-class-name: org.postgresql.Driver
    password: backenduser
    url: jdbc:postgresql://172.17.0.1:5432/backend_test
    username: backenduser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest
welcome:
  message: Welcome to spring boot demo by Kyron!!

profileconstants:
  controllerconstants:
    person: test_value_profile_prod
kyron:
  rabbit:
    mq:
      queue:
        name: cola1
kafka:
  topic:
    person: spring-boot-demo-test
# actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
# exclude actuator endpoints