server:
  port: 8181

applicationconstants:
  controllerconstants:
    person: test_value

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev   
  datasource:
    driver-class-name: org.postgresql.Driver
    password: backenduser
    url: jdbc:postgresql://172.17.0.1:5432/backend_test
    username: backenduser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to spring boot demo by Kyron!!

profileconstants:
  controllerconstants:
    person: test_value_profile_dev

# actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
---

spring:
  profiles: qa  
  datasource:
    driver-class-name: org.postgresql.Driver
    password: backenduser
    url: jdbc:postgresql://172.17.0.1:5432/backend_test
    username: backenduser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to spring boot demo by Kyron!!
  
profileconstants:
  controllerconstants:
    person: test_value_profile_qa

# actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: prod  
  datasource:
    driver-class-name: org.postgresql.Driver
    password: backenduser
    url: jdbc:postgresql://172.17.0.1:5432/backend_test
    username: backenduser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to spring boot demo by Kyron!!

profileconstants:
  controllerconstants:
    person: test_value_profile_prod

# actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  